/**
 * Mock data for frontend development & demo mode
 * This enables the frontend to function fully without a running backend
 */

import type { Repository, AIAction, Commit, Issue } from "./api";

export const mockRepos: Repository[] = [
  {
    id: "repo-001",
    owner: "facebook",
    repo_name: "react",
    installation_id: 10001,
    is_indexed: true,
    health_score: 87,
    last_indexed_at: "2026-03-31T10:00:00Z",
    last_checked_at: "2026-03-31T17:00:00Z",
    created_at: "2026-03-15T08:00:00Z",
  },
  {
    id: "repo-002",
    owner: "vercel",
    repo_name: "next.js",
    installation_id: 10002,
    is_indexed: true,
    health_score: 92,
    last_indexed_at: "2026-03-31T09:00:00Z",
    last_checked_at: "2026-03-31T16:30:00Z",
    created_at: "2026-03-18T12:00:00Z",
  },
  {
    id: "repo-003",
    owner: "langchain-ai",
    repo_name: "langchain",
    installation_id: 10003,
    is_indexed: true,
    health_score: 74,
    last_indexed_at: "2026-03-30T22:00:00Z",
    last_checked_at: "2026-03-31T15:00:00Z",
    created_at: "2026-03-20T14:00:00Z",
  },
  {
    id: "repo-004",
    owner: "openai",
    repo_name: "openai-python",
    installation_id: 10004,
    is_indexed: false,
    health_score: 65,
    last_indexed_at: null,
    last_checked_at: "2026-03-31T12:00:00Z",
    created_at: "2026-03-25T10:00:00Z",
  },
];

export const mockActions: AIAction[] = [
  {
    id: "act-001",
    repo_id: "repo-001",
    event_type: "issue_triage",
    target_type: "issue",
    target_number: 247,
    actions_taken: [
      { action: "add_label", value: "bug" },
      { action: "add_label", value: "needs-repro" },
      { action: "post_comment", value: "Identified as a rendering bug in concurrent mode. Requesting reproduction steps." },
    ],
    reasoning: "ML classifier identified this as a bug with 94% confidence. No duplicate found in ChromaDB. Issue involves React concurrent rendering which @alice has worked on extensively.",
    ml_classification: { type: "bug", confidence: 0.94, scores: { bug: 0.94, feature: 0.04, question: 0.02 } },
    created_at: "2026-03-31T16:45:00Z",
  },
  {
    id: "act-002",
    repo_id: "repo-001",
    event_type: "contributor_help",
    target_type: "issue",
    target_number: 301,
    actions_taken: [
      { action: "post_comment", value: "Based on CONTRIBUTING.md: 1. Fork the repo 2. Run `yarn install` 3. Run `yarn test` to verify setup." },
      { action: "add_label", value: "question" },
      { action: "add_label", value: "answered" },
    ],
    reasoning: "Classified as a question with 89% confidence. RAG search found relevant context in CONTRIBUTING.md and past issue #45. Confidence 0.82 — sufficient to answer directly.",
    ml_classification: { type: "question", confidence: 0.89, scores: { question: 0.89, bug: 0.07, feature: 0.04 } },
    created_at: "2026-03-31T15:30:00Z",
  },
  {
    id: "act-003",
    repo_id: "repo-002",
    event_type: "issue_triage",
    target_type: "issue",
    target_number: 198,
    actions_taken: [
      { action: "add_label", value: "duplicate" },
      { action: "post_comment", value: "This appears to be a duplicate of #142 (similarity: 0.91). The fix was merged in v14.2.3." },
    ],
    reasoning: "ChromaDB duplicate detection found Issue #142 with 0.91 similarity score, exceeding the 0.88 threshold. Both issues describe the same hydration mismatch error.",
    ml_classification: { type: "bug", confidence: 0.88, scores: { bug: 0.88, feature: 0.08, question: 0.04 } },
    created_at: "2026-03-31T14:15:00Z",
  },
  {
    id: "act-004",
    repo_id: "repo-003",
    event_type: "issue_triage",
    target_type: "issue",
    target_number: 512,
    actions_taken: [
      { action: "add_label", value: "enhancement" },
      { action: "post_comment", value: "Feature request acknowledged. This aligns with the planned multi-modal RAG support." },
    ],
    reasoning: "ML classifier identified as feature request with 91% confidence. No duplicates found. Tagged as enhancement for maintainer review.",
    ml_classification: { type: "feature", confidence: 0.91, scores: { feature: 0.91, question: 0.05, bug: 0.04 } },
    created_at: "2026-03-31T13:00:00Z",
  },
  {
    id: "act-005",
    repo_id: "repo-001",
    event_type: "commit_analysis",
    target_type: "commit",
    target_number: 0,
    actions_taken: [
      { action: "classify", value: "breaking_change" },
      { action: "alert", value: "Flagged as breaking change — modifies public API surface" },
    ],
    reasoning: "Commit modifies 12 files including core exports. Contains 'BREAKING' keyword in message. Confidence: 96%.",
    ml_classification: { type: "breaking_change", confidence: 0.96, scores: { breaking_change: 0.96, feature: 0.02, refactor: 0.02 } },
    created_at: "2026-03-31T11:30:00Z",
  },
];

export const mockCommits: Commit[] = [
  {
    id: "cm-001",
    repo_id: "repo-001",
    sha: "a1b2c3d",
    message: "feat: add concurrent rendering support for Suspense boundaries",
    author: "alice",
    committed_at: "2026-03-31T16:00:00Z",
    commit_type: "feature",
    confidence: 0.93,
    is_breaking: false,
    agent_analysis: "Adds new concurrent rendering capabilities. Touches 8 files across the reconciler package. No breaking changes detected.",
    related_issues: [234, 256],
    created_at: "2026-03-31T16:05:00Z",
  },
  {
    id: "cm-002",
    repo_id: "repo-001",
    sha: "d4e5f6a",
    message: "fix: resolve memory leak in useEffect cleanup",
    author: "bob",
    committed_at: "2026-03-31T14:30:00Z",
    commit_type: "bug_fix",
    confidence: 0.97,
    is_breaking: false,
    agent_analysis: "Fixes a critical memory leak where effect cleanup functions were not being called during unmount in StrictMode.",
    related_issues: [247],
    created_at: "2026-03-31T14:35:00Z",
  },
  {
    id: "cm-003",
    repo_id: "repo-001",
    sha: "b7c8d9e",
    message: "BREAKING: remove deprecated createFactory API",
    author: "charlie",
    committed_at: "2026-03-31T12:00:00Z",
    commit_type: "breaking_change",
    confidence: 0.96,
    is_breaking: true,
    agent_analysis: "Removes React.createFactory which was deprecated in v18. Migration path: use JSX or React.createElement directly.",
    related_issues: [189],
    created_at: "2026-03-31T12:05:00Z",
  },
  {
    id: "cm-004",
    repo_id: "repo-001",
    sha: "e1f2a3b",
    message: "docs: update contributing guide with new build steps",
    author: "diana",
    committed_at: "2026-03-31T10:00:00Z",
    commit_type: "docs",
    confidence: 0.99,
    is_breaking: false,
    agent_analysis: "Documentation-only change. Updates build instructions for the new Vite-based dev server.",
    related_issues: [],
    created_at: "2026-03-31T10:05:00Z",
  },
  {
    id: "cm-005",
    repo_id: "repo-001",
    sha: "c4d5e6f",
    message: "refactor: simplify scheduler priority queue implementation",
    author: "alice",
    committed_at: "2026-03-30T22:00:00Z",
    commit_type: "refactor",
    confidence: 0.91,
    is_breaking: false,
    agent_analysis: "Simplifies the internal priority queue from a custom heap to a standard sorted array. Performance impact: negligible for < 1000 tasks.",
    related_issues: [],
    created_at: "2026-03-30T22:05:00Z",
  },
  {
    id: "cm-006",
    repo_id: "repo-001",
    sha: "f7a8b9c",
    message: "test: add integration tests for server components",
    author: "bob",
    committed_at: "2026-03-30T18:00:00Z",
    commit_type: "test",
    confidence: 0.98,
    is_breaking: false,
    agent_analysis: "Adds 12 new integration tests covering RSC streaming, error boundaries, and suspense fallbacks.",
    related_issues: [210],
    created_at: "2026-03-30T18:05:00Z",
  },
];

export const mockIssues: Issue[] = [
  {
    id: "iss-001",
    repo_id: "repo-001",
    github_issue_id: 98001,
    number: 247,
    title: "App crashes on large file upload with concurrent mode",
    body: "When uploading files larger than 50MB with concurrent mode enabled, the app crashes with an out-of-memory error...",
    classified_type: "bug",
    confidence: 0.94,
    is_duplicate: false,
    duplicate_of: null,
    suggested_owner: "alice",
    orbiter_responded: true,
    created_at: "2026-03-31T16:45:00Z",
  },
  {
    id: "iss-002",
    repo_id: "repo-001",
    github_issue_id: 98002,
    number: 301,
    title: "How do I set up the development environment on Windows?",
    body: "I'm trying to contribute to the project but I can't figure out how to set up the dev environment on Windows 11...",
    classified_type: "question",
    confidence: 0.89,
    is_duplicate: false,
    duplicate_of: null,
    suggested_owner: null,
    orbiter_responded: true,
    created_at: "2026-03-31T15:30:00Z",
  },
  {
    id: "iss-003",
    repo_id: "repo-002",
    github_issue_id: 98003,
    number: 198,
    title: "Hydration mismatch error in production build",
    body: "Getting a hydration mismatch error when deploying to Vercel. Works fine in development...",
    classified_type: "bug",
    confidence: 0.88,
    is_duplicate: true,
    duplicate_of: 142,
    suggested_owner: "charlie",
    orbiter_responded: true,
    created_at: "2026-03-31T14:15:00Z",
  },
  {
    id: "iss-004",
    repo_id: "repo-003",
    github_issue_id: 98004,
    number: 512,
    title: "Add support for multi-modal RAG with image embeddings",
    body: "It would be great to support image embeddings alongside text for multi-modal retrieval...",
    classified_type: "feature",
    confidence: 0.91,
    is_duplicate: false,
    duplicate_of: null,
    suggested_owner: null,
    orbiter_responded: true,
    created_at: "2026-03-31T13:00:00Z",
  },
  {
    id: "iss-005",
    repo_id: "repo-001",
    github_issue_id: 98005,
    number: 189,
    title: "createFactory deprecation warnings flood the console",
    body: "Since the latest update, every render cycle generates about 20 deprecation warnings for createFactory...",
    classified_type: "bug",
    confidence: 0.86,
    is_duplicate: false,
    duplicate_of: null,
    suggested_owner: "bob",
    orbiter_responded: true,
    created_at: "2026-03-30T20:00:00Z",
  },
];

export const mockWSEvents = [
  { type: "issue_triaged" as const, issue_number: 247, classification: "bug", actions: ["add_label", "post_comment"], timestamp: "2026-03-31T16:45:00Z" },
  { type: "question_answered" as const, issue_number: 301, confidence: 0.82, timestamp: "2026-03-31T15:30:00Z" },
  { type: "commit_analyzed" as const, sha: "a1b2c3d", commit_type: "feature", timestamp: "2026-03-31T16:05:00Z" },
  { type: "commit_analyzed" as const, sha: "b7c8d9e", commit_type: "breaking_change", timestamp: "2026-03-31T12:05:00Z" },
  { type: "issue_triaged" as const, issue_number: 512, classification: "feature", actions: ["add_label", "post_comment"], timestamp: "2026-03-31T13:00:00Z" },
];
